services:
  web-static:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-web-static
    restart: always
    networks:
      - 10_modules

  web-gateway:
    image: nginx:1.27-alpine
    container_name: auth-web-gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/proxy_headers.conf:/etc/nginx/includes/proxy_headers.conf:ro
    restart: always
    networks:
      - 10_modules

networks:
  10_modules:
    external: true
    name: 10_modules
